### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by AndreasChristensen89** [AndreasChristensen89/My-first-Agile-Project#3]
As a user I can choose to be anonymous so that privacy can be managed

# **Acceptance Criteria**

* Must be provided as a clearly visible checkbox
* Must be located next to the submit button
* Any identity of the user must not be saved in any database after ticking box
* When ticking box/button it must be clearly signalled as marked.

# **Tasks**

- [ ] Update the HTML and CSS to include the checkbox and show the name of the submitter
- [ ] Include field to enter username, anonymous button should set field to not-necessary 
- [ ] Update controller function
- [ ] Update unit test scripts
- [ ] Test functionality
